# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isthiskeanureeves', '0005_page_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
